[W 2022-10-12 11:36:47.493 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-12 11:36:47.493 LabApp] 'allow_root' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-12 11:36:47.493 LabApp] 'allow_root' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-12 11:36:47.493 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-10-12 11:36:47.493 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-10-12 11:36:47.510 LabApp] JupyterLab extension loaded from /home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/site-packages/jupyterlab
[I 2022-10-12 11:36:47.510 LabApp] JupyterLab application directory is /home/sabbir_j/anaconda3/envs/bnlp_env/share/jupyter/lab
[I 11:36:47.518 NotebookApp] The port 8888 is already in use, trying another port.
[I 11:36:47.520 NotebookApp] Serving notebooks from local directory: /home/ansari/codes/spellchecker/bart/codes
[I 11:36:47.520 NotebookApp] Jupyter Notebook 6.4.4 is running at:
[I 11:36:47.520 NotebookApp] http://localhost:8889/
[I 11:36:47.520 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
/home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 11:37:25.188 NotebookApp] Notebook model_analysis.ipynb is not trusted
Exception in callback <TaskWakeupMethWrapper object at 0x7fa42f4c8f70>(<Future finis...ce4"\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x7fa42f4c8f70>(<Future finis...ce4"\r\n\r\n'>)>
Traceback (most recent call last):
  File "/home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-4' coro=<HTTP1ServerConnection._server_request_loop() running at /home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/site-packages/tornado/http1connection.py:823> wait_for=<Future finished result=b'GET /kernel...0ce4"\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/site-packages/tornado/ioloop.py:688]> while another task <Task pending name='Task-1' coro=<MultiKernelManager._async_start_kernel() running at /home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py:186>> is being executed.
[I 11:37:25.876 NotebookApp] Kernel started: 6b1eb475-1ae2-4990-a3fe-c1b1d5fbd6c5, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 056a314f-b8fa-4893-996b-f45b4ac6ace1
/home/sabbir_j/anaconda3/envs/bnlp_env/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 11:39:25.728 NotebookApp] Saving file at /model_analysis.ipynb
[W 11:39:25.729 NotebookApp] Notebook model_analysis.ipynb is not trusted
[I 16:31:50.666 NotebookApp] Starting buffering for 6b1eb475-1ae2-4990-a3fe-c1b1d5fbd6c5:c3c7b69c92c341a785f6a6a21b2f107e
